# Generated by Django 4.1.4 on 2023-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kopi_app", "0002_alter_koordinat_alamat_alter_koordinat_koordinat"),
    ]

    operations = [
        migrations.AddField(
            model_name="koordinat",
            name="nama_cafe",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
