# Generated by Django 4.1.4 on 2023-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kopi_app", "0003_koordinat_nama_cafe"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="keterangan",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
