# Generated by Django 4.1.4 on 2023-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kopi_app", "0004_menu_keterangan"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.AlterField(
            model_name="menu",
            name="keterangan",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
